{ "_id" : 1, "note" : "nur in Maßen genießen!", "name" : "Dal Maharani", "pic_url" : "/static/food_images/1.jpg", "price" : 7.5, "health_score" : 2, "user_rating" : 4, "nutrition" : {}, "food_class" : [], "restaurant" : 1 }
{ "_id" : 2, "note" : "bei der Soße sparen!", "name" : "Saag Alu", "pic_url" : "/static/food_images/2.jpg", "price" : 6, "health_score" : 4, "user_rating" : 4, "nutrition" : {}, "food_class" : [ "vegetarian" ], "restaurant" : 1 }
{ "_id" : 3, "note" : "am besten mit Salat!", "name" : "Chicken Bhuna", "pic_url" : "/static/food_images/3.jpg", "price" : 8, "health_score" : 2, "user_rating" : 0, "nutrition" : {}, "food_class" : [ "chicken" ], "restaurant" : 1 }
{ "_id" : 4, "note" : "dazu ein Wasser!", "name" : "Kashmiri Chicken", "pic_url" : "/static/food_images/4.jpg", "price" : 5.5, "health_score" : 3, "user_rating" : 3, "nutrition" : {}, "food_class" : [ "chicken" ], "restaurant" : 1 }
{ "_id" : 5, "note" : "dazu Reis!", "name" : "Dal Goasht", "pic_url" : "/static/food_images/5.jpg", "price" : 7, "health_score" : 3, "user_rating" : 3, "nutrition" : {}, "food_class" : [ "lamb" ], "restaurant" : 1 }
{ "_id" : 6, "note" : "Zuschlagen!", "name" : "Fish Tikka", "pic_url" : "/static/food_images/6.jpg", "price" : 8.5, "health_score" : 5, "user_rating" : 2, "nutrition" : {}, "food_class" : [ "fish" ], "restaurant" : 1 }
{ "_id" : 7, "note" : "lecker mit Dip!", "name" : "Tandoori Chicken", "pic_url" : "/static/food_images/7.jpg", "price" : 5.5, "health_score" : 4, "user_rating" : 3, "nutrition" : {}, "food_class" : [ "chicken" ], "restaurant" : 1 }
{ "_id" : 8, "note" : "beim Dressing sparen!", "name" : "Punjabi Salat", "pic_url" : "/static/food_images/8.jpg", "price" : 5.5, "health_score" : 4, "user_rating" : 0, "nutrition" : {}, "food_class" : [ "salad", "vegetarian" ], "restaurant" : 1 }
{ "_id" : 9, "note" : "dazu Reis!", "name" : "Bhindi Masala", "pic_url" : "/static/food_images/9.jpg", "price" : 10.9, "health_score" : 4, "user_rating" : 5, "nutrition" : {}, "food_class" : [ "vegetarian" ], "restaurant" : 1 }
{ "_id" : 10, "note" : "Nachtisch auslassen!", "name" : "Karahi Paneer", "pic_url" : "/static/food_images/10.jpg", "price" : 11.50, "health_score" : 3, "user_rating" : 5, "nutrition" : {}, "food_class" : [ "lamb" ], "restaurant" : 1 }
{ "_id" : 11, "note" : "ein wenig Brot dazu!", "name" : "Tom Kha Gai", "pic_url" : "/static/food_images/11.jpg", "price" : 4, "health_score" : 4, "user_rating" : 2, "nutrition" : {}, "food_class" : [], "restaurant" : 2 }
{ "_id" : 12, "note" : "drei reichen!", "name" : "Frühlingsrolle Thai Art", "pic_url" : "/static/food_images/12.jpg", "price" : 2.5, "health_score" : 3, "user_rating" : 3, "nutrition" : {}, "food_class" : [ "vegetarian" ], "restaurant" : 2 }
{ "_id" : 13, "note" : "reichlich dippen!", "name" : "Sate-Spieße", "pic_url" : "/static/food_images/13.jpg", "price" : 4.5, "health_score" : 3, "user_rating" : 5, "nutrition" : {}, "food_class" : [], "restaurant" : 2 }
{ "_id" : 14, "note" : "bei der Soße sparen!", "name" : "Glasnudel-Salat", "pic_url" : "/static/food_images/14.jpg", "price" : 7.4, "health_score" : 4, "user_rating" : 3, "nutrition" : {}, "food_class" : [], "restaurant" : 2 }
{ "_id" : 15, "note" : "Zuschlagen!", "name" : "Wok-Gemüse mit rotem Curry, Kokos", "pic_url" : "/static/food_images/15.jpg", "price" : 6, "health_score" : 5, "user_rating" : 4, "nutrition" : {}, "food_class" : [], "restaurant" : 2 }
{ "_id" : 16, "note" : "Hong Kong Phooey", "name" : "Chop-Suey mit Huhn", "pic_url" : "/static/food_images/16.jpg", "price" : 6.9, "health_score" : 4, "user_rating" : 3, "nutrition" : {}, "food_class" : [], "restaurant" : 2 }
{ "_id" : 17, "note" : "Ducktales", "name" : "Knusprige Ente-Salat", "pic_url" : "/static/food_images/17.jpg", "price" : 8.3, "health_score" : 3, "user_rating" : 5, "nutrition" : {}, "food_class" : [], "restaurant" : 2 }
{ "_id" : 18, "note" : "spider-pig!", "name" : "Gung Pao mit Schwein", "pic_url" : "/static/food_images/18.jpg", "price" : 6.9, "health_score" : 2, "user_rating" : 5, "nutrition" : {}, "food_class" : [], "restaurant" : 2 }
{ "_id" : 19, "note" : "am besten mit Salat!", "name" : "Reis gebraten mit Ei", "pic_url" : "/static/food_images/19.jpg", "price" : 6, "health_score" : 3, "user_rating" : 1, "nutrition" : {}, "food_class" : ["vegetarian"], "restaurant" : 2 }
{ "_id" : 20, "note" : "dazu ein Wasser!", "name" : "Curry mit Tofu", "pic_url" : "/static/food_images/20.jpg", "price" : 6, "health_score" : 4, "user_rating" : 1, "nutrition" : {}, "food_class" : ["vegetarian"], "restaurant" : 2 }